/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Bahan: () => import('#controllers/bahan_controller'),
  HakAkses: () => import('#controllers/hak_akses_controller'),
  IntegrasiWhatsapp: () => import('#controllers/integrasi_whatsapp_controller'),
  KategoriProduk: () => import('#controllers/kategori_produk_controller'),
  Pengguna: () => import('#controllers/pengguna_controller'),
  Produk: () => import('#controllers/produk_controller'),
  Produksi: () => import('#controllers/produksi_controller'),
  Resep: () => import('#controllers/resep_controller'),
  RiwayatProduksi: () => import('#controllers/riwayat_produksi_controller'),
  RiwayatStokBahanBaku: () => import('#controllers/riwayat_stok_bahan_baku'),
  RiwayatStokProduk: () => import('#controllers/riwayat_stok_produk_controller'),
  StokBahan: () => import('#controllers/stok_bahan_controller'),
  StokProduk: () => import('#controllers/stok_produk_controller'),
}
