/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Bahan: () => import('#controllers/bahan_controller'),
  HakAkses: () => import('#controllers/hak_akses_controller'),
  Pengguna: () => import('#controllers/pengguna_controller'),
  Produk: () => import('#controllers/produk_controller'),
}
