/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class TbBahanBakuSchema extends BaseModel {
  static $columns = ['idBahanBaku', 'namaBahanBaku', 'satuan', 'createdAt'] as const
  $columns = TbBahanBakuSchema.$columns
  @column()
  declare idBahanBaku: number
  @column()
  declare namaBahanBaku: string
  @column()
  declare satuan: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class TbHakAkseSchema extends BaseModel {
  static $columns = ['idHakAkses', 'namaHakAkses', 'createdAt'] as const
  $columns = TbHakAkseSchema.$columns
  @column()
  declare idHakAkses: number
  @column()
  declare namaHakAkses: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class TbKategoriSchema extends BaseModel {
  static $columns = ['idKategori', 'namaKategori'] as const
  $columns = TbKategoriSchema.$columns
  @column()
  declare idKategori: number
  @column()
  declare namaKategori: string
}

export class TbPenggunaSchema extends BaseModel {
  static $columns = ['id', 'idPengguna', 'idHakAkses', 'namaPengguna', 'nomorTelepon', 'createdAt'] as const
  $columns = TbPenggunaSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idPengguna: string
  @column()
  declare idHakAkses: number | null
  @column()
  declare namaPengguna: string | null
  @column()
  declare nomorTelepon: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class TbProdukSchema extends BaseModel {
  static $columns = ['idProduk', 'idKategori', 'namaProduk', 'satuan', 'createdAt'] as const
  $columns = TbProdukSchema.$columns
  @column()
  declare idProduk: number
  @column()
  declare idKategori: number | null
  @column()
  declare namaProduk: string
  @column()
  declare satuan: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}
