/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.login': {
    methods: ["GET","HEAD"],
    pattern: '/',
    tokens: [{"old":"/","type":0,"val":"/","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.sign_in': {
    methods: ["POST"],
    pattern: '/login',
    tokens: [{"old":"/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.sign_in']['types'],
  },
  'webhook.get_stok_produk_from_supabase': {
    methods: ["POST"],
    pattern: '/webhook/stok-produk',
    tokens: [{"old":"/webhook/stok-produk","type":0,"val":"webhook","end":""},{"old":"/webhook/stok-produk","type":0,"val":"stok-produk","end":""}],
    types: placeholder as Registry['webhook.get_stok_produk_from_supabase']['types'],
  },
  'webhook.get_stok_bahan_baku_from_supabase': {
    methods: ["POST"],
    pattern: '/webhook/bahan',
    tokens: [{"old":"/webhook/bahan","type":0,"val":"webhook","end":""},{"old":"/webhook/bahan","type":0,"val":"bahan","end":""}],
    types: placeholder as Registry['webhook.get_stok_bahan_baku_from_supabase']['types'],
  },
  'webhook.get_produksi_from_supabase': {
    methods: ["POST"],
    pattern: '/webhook/produksi',
    tokens: [{"old":"/webhook/produksi","type":0,"val":"webhook","end":""},{"old":"/webhook/produksi","type":0,"val":"produksi","end":""}],
    types: placeholder as Registry['webhook.get_produksi_from_supabase']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'stokBahan.index': {
    methods: ["GET","HEAD"],
    pattern: '/stok-bahan',
    tokens: [{"old":"/stok-bahan","type":0,"val":"stok-bahan","end":""}],
    types: placeholder as Registry['stokBahan.index']['types'],
  },
  'stokBahan.search': {
    methods: ["GET","HEAD"],
    pattern: '/stok-bahan/search',
    tokens: [{"old":"/stok-bahan/search","type":0,"val":"stok-bahan","end":""},{"old":"/stok-bahan/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['stokBahan.search']['types'],
  },
  'stokProduk.index': {
    methods: ["GET","HEAD"],
    pattern: '/stok-produk',
    tokens: [{"old":"/stok-produk","type":0,"val":"stok-produk","end":""}],
    types: placeholder as Registry['stokProduk.index']['types'],
  },
  'stokProduk.search': {
    methods: ["GET","HEAD"],
    pattern: '/stok-produk/search',
    tokens: [{"old":"/stok-produk/search","type":0,"val":"stok-produk","end":""},{"old":"/stok-produk/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['stokProduk.search']['types'],
  },
  'restokBahan.restok': {
    methods: ["GET","HEAD"],
    pattern: '/restok-bahan',
    tokens: [{"old":"/restok-bahan","type":0,"val":"restok-bahan","end":""}],
    types: placeholder as Registry['restokBahan.restok']['types'],
  },
  'restokBahan.create': {
    methods: ["POST"],
    pattern: '/restok-bahan/create',
    tokens: [{"old":"/restok-bahan/create","type":0,"val":"restok-bahan","end":""},{"old":"/restok-bahan/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['restokBahan.create']['types'],
  },
  'stokBahanBaku.adjustment': {
    methods: ["GET","HEAD"],
    pattern: '/stok-bahan-baku/adjustment',
    tokens: [{"old":"/stok-bahan-baku/adjustment","type":0,"val":"stok-bahan-baku","end":""},{"old":"/stok-bahan-baku/adjustment","type":0,"val":"adjustment","end":""}],
    types: placeholder as Registry['stokBahanBaku.adjustment']['types'],
  },
  'stokBahanBaku.createAdjustment': {
    methods: ["POST"],
    pattern: '/stok-bahan-baku/adjustment/create',
    tokens: [{"old":"/stok-bahan-baku/adjustment/create","type":0,"val":"stok-bahan-baku","end":""},{"old":"/stok-bahan-baku/adjustment/create","type":0,"val":"adjustment","end":""},{"old":"/stok-bahan-baku/adjustment/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['stokBahanBaku.createAdjustment']['types'],
  },
  'stokBahanBaku.status': {
    methods: ["GET","HEAD"],
    pattern: '/stok-bahan-baku/status',
    tokens: [{"old":"/stok-bahan-baku/status","type":0,"val":"stok-bahan-baku","end":""},{"old":"/stok-bahan-baku/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['stokBahanBaku.status']['types'],
  },
  'stokProduk.adjustment': {
    methods: ["GET","HEAD"],
    pattern: '/stok-produk/adjustment',
    tokens: [{"old":"/stok-produk/adjustment","type":0,"val":"stok-produk","end":""},{"old":"/stok-produk/adjustment","type":0,"val":"adjustment","end":""}],
    types: placeholder as Registry['stokProduk.adjustment']['types'],
  },
  'stokProduk.createAdjustment': {
    methods: ["POST"],
    pattern: '/stok-produk/adjustment/create',
    tokens: [{"old":"/stok-produk/adjustment/create","type":0,"val":"stok-produk","end":""},{"old":"/stok-produk/adjustment/create","type":0,"val":"adjustment","end":""},{"old":"/stok-produk/adjustment/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['stokProduk.createAdjustment']['types'],
  },
  'stokProduk.status': {
    methods: ["GET","HEAD"],
    pattern: '/stok-produk/status',
    tokens: [{"old":"/stok-produk/status","type":0,"val":"stok-produk","end":""},{"old":"/stok-produk/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['stokProduk.status']['types'],
  },
  'resep.index': {
    methods: ["GET","HEAD"],
    pattern: '/resep',
    tokens: [{"old":"/resep","type":0,"val":"resep","end":""}],
    types: placeholder as Registry['resep.index']['types'],
  },
  'resep.create': {
    methods: ["POST"],
    pattern: '/resep/create',
    tokens: [{"old":"/resep/create","type":0,"val":"resep","end":""},{"old":"/resep/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['resep.create']['types'],
  },
  'resep.edit': {
    methods: ["GET","HEAD"],
    pattern: '/resep/edit/:id',
    tokens: [{"old":"/resep/edit/:id","type":0,"val":"resep","end":""},{"old":"/resep/edit/:id","type":0,"val":"edit","end":""},{"old":"/resep/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['resep.edit']['types'],
  },
  'resep.update': {
    methods: ["PUT"],
    pattern: '/resep/update/:id',
    tokens: [{"old":"/resep/update/:id","type":0,"val":"resep","end":""},{"old":"/resep/update/:id","type":0,"val":"update","end":""},{"old":"/resep/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['resep.update']['types'],
  },
  'resep.destroy': {
    methods: ["DELETE"],
    pattern: '/resep/delete/:id',
    tokens: [{"old":"/resep/delete/:id","type":0,"val":"resep","end":""},{"old":"/resep/delete/:id","type":0,"val":"delete","end":""},{"old":"/resep/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['resep.destroy']['types'],
  },
  'resep.search': {
    methods: ["GET","HEAD"],
    pattern: '/resep/search',
    tokens: [{"old":"/resep/search","type":0,"val":"resep","end":""},{"old":"/resep/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['resep.search']['types'],
  },
  'resep.trash': {
    methods: ["GET","HEAD"],
    pattern: '/resep/trash',
    tokens: [{"old":"/resep/trash","type":0,"val":"resep","end":""},{"old":"/resep/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['resep.trash']['types'],
  },
  'resep.restore': {
    methods: ["PATCH"],
    pattern: '/resep/restore/:id',
    tokens: [{"old":"/resep/restore/:id","type":0,"val":"resep","end":""},{"old":"/resep/restore/:id","type":0,"val":"restore","end":""},{"old":"/resep/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['resep.restore']['types'],
  },
  'resep.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/resep/trash/search',
    tokens: [{"old":"/resep/trash/search","type":0,"val":"resep","end":""},{"old":"/resep/trash/search","type":0,"val":"trash","end":""},{"old":"/resep/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['resep.searchTrash']['types'],
  },
  'produksi.index': {
    methods: ["GET","HEAD"],
    pattern: '/produksi',
    tokens: [{"old":"/produksi","type":0,"val":"produksi","end":""}],
    types: placeholder as Registry['produksi.index']['types'],
  },
  'produksi.create': {
    methods: ["POST"],
    pattern: '/produksi/create',
    tokens: [{"old":"/produksi/create","type":0,"val":"produksi","end":""},{"old":"/produksi/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['produksi.create']['types'],
  },
  'bahan.index': {
    methods: ["GET","HEAD"],
    pattern: '/bahan',
    tokens: [{"old":"/bahan","type":0,"val":"bahan","end":""}],
    types: placeholder as Registry['bahan.index']['types'],
  },
  'bahan.edit': {
    methods: ["GET","HEAD"],
    pattern: '/bahan/edit/:id',
    tokens: [{"old":"/bahan/edit/:id","type":0,"val":"bahan","end":""},{"old":"/bahan/edit/:id","type":0,"val":"edit","end":""},{"old":"/bahan/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bahan.edit']['types'],
  },
  'bahan.create': {
    methods: ["POST"],
    pattern: '/bahan/create',
    tokens: [{"old":"/bahan/create","type":0,"val":"bahan","end":""},{"old":"/bahan/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['bahan.create']['types'],
  },
  'bahan.update': {
    methods: ["PUT"],
    pattern: '/bahan/update/:id',
    tokens: [{"old":"/bahan/update/:id","type":0,"val":"bahan","end":""},{"old":"/bahan/update/:id","type":0,"val":"update","end":""},{"old":"/bahan/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bahan.update']['types'],
  },
  'bahan.destroy': {
    methods: ["DELETE"],
    pattern: '/bahan/delete/:id',
    tokens: [{"old":"/bahan/delete/:id","type":0,"val":"bahan","end":""},{"old":"/bahan/delete/:id","type":0,"val":"delete","end":""},{"old":"/bahan/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bahan.destroy']['types'],
  },
  'bahan.search': {
    methods: ["GET","HEAD"],
    pattern: '/bahan/search',
    tokens: [{"old":"/bahan/search","type":0,"val":"bahan","end":""},{"old":"/bahan/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['bahan.search']['types'],
  },
  'bahan.trash': {
    methods: ["GET","HEAD"],
    pattern: '/bahan/trash',
    tokens: [{"old":"/bahan/trash","type":0,"val":"bahan","end":""},{"old":"/bahan/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['bahan.trash']['types'],
  },
  'bahan.restore': {
    methods: ["PATCH"],
    pattern: '/bahan/restore/:id',
    tokens: [{"old":"/bahan/restore/:id","type":0,"val":"bahan","end":""},{"old":"/bahan/restore/:id","type":0,"val":"restore","end":""},{"old":"/bahan/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['bahan.restore']['types'],
  },
  'bahan.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/bahan/trash/search',
    tokens: [{"old":"/bahan/trash/search","type":0,"val":"bahan","end":""},{"old":"/bahan/trash/search","type":0,"val":"trash","end":""},{"old":"/bahan/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['bahan.searchTrash']['types'],
  },
  'approval-stok-bahan-baku.index': {
    methods: ["GET","HEAD"],
    pattern: '/approval-stok-bahan-baku',
    tokens: [{"old":"/approval-stok-bahan-baku","type":0,"val":"approval-stok-bahan-baku","end":""}],
    types: placeholder as Registry['approval-stok-bahan-baku.index']['types'],
  },
  'approval-stok-bahan-baku.approve': {
    methods: ["POST"],
    pattern: '/approval-stok-bahan-baku/approve/:id',
    tokens: [{"old":"/approval-stok-bahan-baku/approve/:id","type":0,"val":"approval-stok-bahan-baku","end":""},{"old":"/approval-stok-bahan-baku/approve/:id","type":0,"val":"approve","end":""},{"old":"/approval-stok-bahan-baku/approve/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['approval-stok-bahan-baku.approve']['types'],
  },
  'approval-stok-bahan-baku.reject': {
    methods: ["POST"],
    pattern: '/approval-stok-bahan-baku/reject/:id',
    tokens: [{"old":"/approval-stok-bahan-baku/reject/:id","type":0,"val":"approval-stok-bahan-baku","end":""},{"old":"/approval-stok-bahan-baku/reject/:id","type":0,"val":"reject","end":""},{"old":"/approval-stok-bahan-baku/reject/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['approval-stok-bahan-baku.reject']['types'],
  },
  'approval-stok-bahan-baku.search': {
    methods: ["GET","HEAD"],
    pattern: '/approval-stok-bahan-baku/search',
    tokens: [{"old":"/approval-stok-bahan-baku/search","type":0,"val":"approval-stok-bahan-baku","end":""},{"old":"/approval-stok-bahan-baku/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['approval-stok-bahan-baku.search']['types'],
  },
  'produk.index': {
    methods: ["GET","HEAD"],
    pattern: '/produk',
    tokens: [{"old":"/produk","type":0,"val":"produk","end":""}],
    types: placeholder as Registry['produk.index']['types'],
  },
  'produk.create': {
    methods: ["POST"],
    pattern: '/produk/create',
    tokens: [{"old":"/produk/create","type":0,"val":"produk","end":""},{"old":"/produk/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['produk.create']['types'],
  },
  'produk.edit': {
    methods: ["GET","HEAD"],
    pattern: '/produk/edit/:id',
    tokens: [{"old":"/produk/edit/:id","type":0,"val":"produk","end":""},{"old":"/produk/edit/:id","type":0,"val":"edit","end":""},{"old":"/produk/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['produk.edit']['types'],
  },
  'produk.update': {
    methods: ["PUT"],
    pattern: '/produk/update/:id',
    tokens: [{"old":"/produk/update/:id","type":0,"val":"produk","end":""},{"old":"/produk/update/:id","type":0,"val":"update","end":""},{"old":"/produk/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['produk.update']['types'],
  },
  'produk.destroy': {
    methods: ["DELETE"],
    pattern: '/produk/delete/:id',
    tokens: [{"old":"/produk/delete/:id","type":0,"val":"produk","end":""},{"old":"/produk/delete/:id","type":0,"val":"delete","end":""},{"old":"/produk/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['produk.destroy']['types'],
  },
  'produk.search': {
    methods: ["GET","HEAD"],
    pattern: '/produk/search',
    tokens: [{"old":"/produk/search","type":0,"val":"produk","end":""},{"old":"/produk/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['produk.search']['types'],
  },
  'produk.trash': {
    methods: ["GET","HEAD"],
    pattern: '/produk/trash',
    tokens: [{"old":"/produk/trash","type":0,"val":"produk","end":""},{"old":"/produk/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['produk.trash']['types'],
  },
  'produk.restore': {
    methods: ["PATCH"],
    pattern: '/produk/restore/:id',
    tokens: [{"old":"/produk/restore/:id","type":0,"val":"produk","end":""},{"old":"/produk/restore/:id","type":0,"val":"restore","end":""},{"old":"/produk/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['produk.restore']['types'],
  },
  'produk.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/produk/trash/search',
    tokens: [{"old":"/produk/trash/search","type":0,"val":"produk","end":""},{"old":"/produk/trash/search","type":0,"val":"trash","end":""},{"old":"/produk/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['produk.searchTrash']['types'],
  },
  'approval-stok-produk.index': {
    methods: ["GET","HEAD"],
    pattern: '/approval-stok-produk',
    tokens: [{"old":"/approval-stok-produk","type":0,"val":"approval-stok-produk","end":""}],
    types: placeholder as Registry['approval-stok-produk.index']['types'],
  },
  'approval-stok-produk.approve': {
    methods: ["POST"],
    pattern: '/approval-stok-produk/approve/:id',
    tokens: [{"old":"/approval-stok-produk/approve/:id","type":0,"val":"approval-stok-produk","end":""},{"old":"/approval-stok-produk/approve/:id","type":0,"val":"approve","end":""},{"old":"/approval-stok-produk/approve/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['approval-stok-produk.approve']['types'],
  },
  'approval-stok-produk.reject': {
    methods: ["POST"],
    pattern: '/approval-stok-produk/reject/:id',
    tokens: [{"old":"/approval-stok-produk/reject/:id","type":0,"val":"approval-stok-produk","end":""},{"old":"/approval-stok-produk/reject/:id","type":0,"val":"reject","end":""},{"old":"/approval-stok-produk/reject/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['approval-stok-produk.reject']['types'],
  },
  'approval-stok-produk.search': {
    methods: ["GET","HEAD"],
    pattern: '/approval-stok-produk/search',
    tokens: [{"old":"/approval-stok-produk/search","type":0,"val":"approval-stok-produk","end":""},{"old":"/approval-stok-produk/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['approval-stok-produk.search']['types'],
  },
  'hakAkses.index': {
    methods: ["GET","HEAD"],
    pattern: '/role',
    tokens: [{"old":"/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['hakAkses.index']['types'],
  },
  'hakAkses.create': {
    methods: ["POST"],
    pattern: '/role/create',
    tokens: [{"old":"/role/create","type":0,"val":"role","end":""},{"old":"/role/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['hakAkses.create']['types'],
  },
  'hakAkses.edit': {
    methods: ["GET","HEAD"],
    pattern: '/role/edit/:id',
    tokens: [{"old":"/role/edit/:id","type":0,"val":"role","end":""},{"old":"/role/edit/:id","type":0,"val":"edit","end":""},{"old":"/role/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hakAkses.edit']['types'],
  },
  'hakAkses.update': {
    methods: ["PUT"],
    pattern: '/role/update/:id',
    tokens: [{"old":"/role/update/:id","type":0,"val":"role","end":""},{"old":"/role/update/:id","type":0,"val":"update","end":""},{"old":"/role/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hakAkses.update']['types'],
  },
  'hakAkses.destroy': {
    methods: ["DELETE"],
    pattern: '/role/delete/:id',
    tokens: [{"old":"/role/delete/:id","type":0,"val":"role","end":""},{"old":"/role/delete/:id","type":0,"val":"delete","end":""},{"old":"/role/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hakAkses.destroy']['types'],
  },
  'hakAkses.search': {
    methods: ["GET","HEAD"],
    pattern: '/role/search',
    tokens: [{"old":"/role/search","type":0,"val":"role","end":""},{"old":"/role/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['hakAkses.search']['types'],
  },
  'hakAkses.trash': {
    methods: ["GET","HEAD"],
    pattern: '/role/trash',
    tokens: [{"old":"/role/trash","type":0,"val":"role","end":""},{"old":"/role/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['hakAkses.trash']['types'],
  },
  'hakAkses.restore': {
    methods: ["PATCH"],
    pattern: '/role/restore/:id',
    tokens: [{"old":"/role/restore/:id","type":0,"val":"role","end":""},{"old":"/role/restore/:id","type":0,"val":"restore","end":""},{"old":"/role/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['hakAkses.restore']['types'],
  },
  'hakAkses.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/role/trash/search',
    tokens: [{"old":"/role/trash/search","type":0,"val":"role","end":""},{"old":"/role/trash/search","type":0,"val":"trash","end":""},{"old":"/role/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['hakAkses.searchTrash']['types'],
  },
  'pengguna.index': {
    methods: ["GET","HEAD"],
    pattern: '/pengguna',
    tokens: [{"old":"/pengguna","type":0,"val":"pengguna","end":""}],
    types: placeholder as Registry['pengguna.index']['types'],
  },
  'pengguna.create': {
    methods: ["POST"],
    pattern: '/pengguna/create',
    tokens: [{"old":"/pengguna/create","type":0,"val":"pengguna","end":""},{"old":"/pengguna/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['pengguna.create']['types'],
  },
  'pengguna.edit': {
    methods: ["GET","HEAD"],
    pattern: '/pengguna/edit/:id',
    tokens: [{"old":"/pengguna/edit/:id","type":0,"val":"pengguna","end":""},{"old":"/pengguna/edit/:id","type":0,"val":"edit","end":""},{"old":"/pengguna/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pengguna.edit']['types'],
  },
  'pengguna.update': {
    methods: ["PUT"],
    pattern: '/pengguna/update/:id',
    tokens: [{"old":"/pengguna/update/:id","type":0,"val":"pengguna","end":""},{"old":"/pengguna/update/:id","type":0,"val":"update","end":""},{"old":"/pengguna/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pengguna.update']['types'],
  },
  'pengguna.destroy': {
    methods: ["DELETE"],
    pattern: '/pengguna/delete/:id',
    tokens: [{"old":"/pengguna/delete/:id","type":0,"val":"pengguna","end":""},{"old":"/pengguna/delete/:id","type":0,"val":"delete","end":""},{"old":"/pengguna/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pengguna.destroy']['types'],
  },
  'pengguna.search': {
    methods: ["GET","HEAD"],
    pattern: '/pengguna/search',
    tokens: [{"old":"/pengguna/search","type":0,"val":"pengguna","end":""},{"old":"/pengguna/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['pengguna.search']['types'],
  },
  'pengguna.trash': {
    methods: ["GET","HEAD"],
    pattern: '/pengguna/trash',
    tokens: [{"old":"/pengguna/trash","type":0,"val":"pengguna","end":""},{"old":"/pengguna/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['pengguna.trash']['types'],
  },
  'pengguna.restore': {
    methods: ["PATCH"],
    pattern: '/pengguna/restore/:id',
    tokens: [{"old":"/pengguna/restore/:id","type":0,"val":"pengguna","end":""},{"old":"/pengguna/restore/:id","type":0,"val":"restore","end":""},{"old":"/pengguna/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['pengguna.restore']['types'],
  },
  'pengguna.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/pengguna/trash/search',
    tokens: [{"old":"/pengguna/trash/search","type":0,"val":"pengguna","end":""},{"old":"/pengguna/trash/search","type":0,"val":"trash","end":""},{"old":"/pengguna/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['pengguna.searchTrash']['types'],
  },
  'kategoriProduk.index': {
    methods: ["GET","HEAD"],
    pattern: '/kategori-produk',
    tokens: [{"old":"/kategori-produk","type":0,"val":"kategori-produk","end":""}],
    types: placeholder as Registry['kategoriProduk.index']['types'],
  },
  'kategoriProduk.create': {
    methods: ["POST"],
    pattern: '/kategori-produk/create',
    tokens: [{"old":"/kategori-produk/create","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['kategoriProduk.create']['types'],
  },
  'kategoriProduk.edit': {
    methods: ["GET","HEAD"],
    pattern: '/kategori-produk/edit/:id',
    tokens: [{"old":"/kategori-produk/edit/:id","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/edit/:id","type":0,"val":"edit","end":""},{"old":"/kategori-produk/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['kategoriProduk.edit']['types'],
  },
  'kategoriProduk.update': {
    methods: ["PUT"],
    pattern: '/kategori-produk/update/:id',
    tokens: [{"old":"/kategori-produk/update/:id","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/update/:id","type":0,"val":"update","end":""},{"old":"/kategori-produk/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['kategoriProduk.update']['types'],
  },
  'kategoriProduk.destroy': {
    methods: ["DELETE"],
    pattern: '/kategori-produk/delete/:id',
    tokens: [{"old":"/kategori-produk/delete/:id","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/delete/:id","type":0,"val":"delete","end":""},{"old":"/kategori-produk/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['kategoriProduk.destroy']['types'],
  },
  'kategoriProduk.search': {
    methods: ["GET","HEAD"],
    pattern: '/kategori-produk/search',
    tokens: [{"old":"/kategori-produk/search","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['kategoriProduk.search']['types'],
  },
  'kategoriProduk.trash': {
    methods: ["GET","HEAD"],
    pattern: '/kategori-produk/trash',
    tokens: [{"old":"/kategori-produk/trash","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/trash","type":0,"val":"trash","end":""}],
    types: placeholder as Registry['kategoriProduk.trash']['types'],
  },
  'kategoriProduk.restore': {
    methods: ["PATCH"],
    pattern: '/kategori-produk/restore/:id',
    tokens: [{"old":"/kategori-produk/restore/:id","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/restore/:id","type":0,"val":"restore","end":""},{"old":"/kategori-produk/restore/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['kategoriProduk.restore']['types'],
  },
  'kategoriProduk.searchTrash': {
    methods: ["GET","HEAD"],
    pattern: '/kategori-produk/trash/search',
    tokens: [{"old":"/kategori-produk/trash/search","type":0,"val":"kategori-produk","end":""},{"old":"/kategori-produk/trash/search","type":0,"val":"trash","end":""},{"old":"/kategori-produk/trash/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['kategoriProduk.searchTrash']['types'],
  },
  'riwayatStokBahanBaku.index': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-bahan-baku',
    tokens: [{"old":"/riwayat-stok-bahan-baku","type":0,"val":"riwayat-stok-bahan-baku","end":""}],
    types: placeholder as Registry['riwayatStokBahanBaku.index']['types'],
  },
  'riwayatStokBahanBaku.filter': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-bahan-baku/filter',
    tokens: [{"old":"/riwayat-stok-bahan-baku/filter","type":0,"val":"riwayat-stok-bahan-baku","end":""},{"old":"/riwayat-stok-bahan-baku/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['riwayatStokBahanBaku.filter']['types'],
  },
  'riwayatStokBahanBaku.generate': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-bahan-baku/generate-pdf',
    tokens: [{"old":"/riwayat-stok-bahan-baku/generate-pdf","type":0,"val":"riwayat-stok-bahan-baku","end":""},{"old":"/riwayat-stok-bahan-baku/generate-pdf","type":0,"val":"generate-pdf","end":""}],
    types: placeholder as Registry['riwayatStokBahanBaku.generate']['types'],
  },
  'riwayatStokProduk.index': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-produk',
    tokens: [{"old":"/riwayat-stok-produk","type":0,"val":"riwayat-stok-produk","end":""}],
    types: placeholder as Registry['riwayatStokProduk.index']['types'],
  },
  'riwayatStokProduk.filter': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-produk/filter',
    tokens: [{"old":"/riwayat-stok-produk/filter","type":0,"val":"riwayat-stok-produk","end":""},{"old":"/riwayat-stok-produk/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['riwayatStokProduk.filter']['types'],
  },
  'riwayatStokProduk.generate': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-stok-produk/generate-pdf',
    tokens: [{"old":"/riwayat-stok-produk/generate-pdf","type":0,"val":"riwayat-stok-produk","end":""},{"old":"/riwayat-stok-produk/generate-pdf","type":0,"val":"generate-pdf","end":""}],
    types: placeholder as Registry['riwayatStokProduk.generate']['types'],
  },
  'riwayatProduksi.index': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-produksi',
    tokens: [{"old":"/riwayat-produksi","type":0,"val":"riwayat-produksi","end":""}],
    types: placeholder as Registry['riwayatProduksi.index']['types'],
  },
  'riwayatProduksi.filter': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-produksi/filter',
    tokens: [{"old":"/riwayat-produksi/filter","type":0,"val":"riwayat-produksi","end":""},{"old":"/riwayat-produksi/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['riwayatProduksi.filter']['types'],
  },
  'riwayatProduksi.generate': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-produksi/generate-pdf',
    tokens: [{"old":"/riwayat-produksi/generate-pdf","type":0,"val":"riwayat-produksi","end":""},{"old":"/riwayat-produksi/generate-pdf","type":0,"val":"generate-pdf","end":""}],
    types: placeholder as Registry['riwayatProduksi.generate']['types'],
  },
  'notifikasiWhatsapp.index': {
    methods: ["GET","HEAD"],
    pattern: '/notifikasi-whatsapp',
    tokens: [{"old":"/notifikasi-whatsapp","type":0,"val":"notifikasi-whatsapp","end":""}],
    types: placeholder as Registry['notifikasiWhatsapp.index']['types'],
  },
  'notifikasiWhatsapp.createSession': {
    methods: ["POST"],
    pattern: '/notifikasi-whatsapp/createSession',
    tokens: [{"old":"/notifikasi-whatsapp/createSession","type":0,"val":"notifikasi-whatsapp","end":""},{"old":"/notifikasi-whatsapp/createSession","type":0,"val":"createSession","end":""}],
    types: placeholder as Registry['notifikasiWhatsapp.createSession']['types'],
  },
  'notifikasiWhatsapp.getQr': {
    methods: ["GET","HEAD"],
    pattern: '/notifikasi-whatsapp/get-qr',
    tokens: [{"old":"/notifikasi-whatsapp/get-qr","type":0,"val":"notifikasi-whatsapp","end":""},{"old":"/notifikasi-whatsapp/get-qr","type":0,"val":"get-qr","end":""}],
    types: placeholder as Registry['notifikasiWhatsapp.getQr']['types'],
  },
  'notifikasiWhatsapp.deleteSession': {
    methods: ["DELETE"],
    pattern: '/notifikasi-whatsapp/deleteSession',
    tokens: [{"old":"/notifikasi-whatsapp/deleteSession","type":0,"val":"notifikasi-whatsapp","end":""},{"old":"/notifikasi-whatsapp/deleteSession","type":0,"val":"deleteSession","end":""}],
    types: placeholder as Registry['notifikasiWhatsapp.deleteSession']['types'],
  },
  'riwayatNotifikasi.index': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-notifikasi',
    tokens: [{"old":"/riwayat-notifikasi","type":0,"val":"riwayat-notifikasi","end":""}],
    types: placeholder as Registry['riwayatNotifikasi.index']['types'],
  },
  'riwayatNotifikasi.filter': {
    methods: ["GET","HEAD"],
    pattern: '/riwayat-notifikasi/filter',
    tokens: [{"old":"/riwayat-notifikasi/filter","type":0,"val":"riwayat-notifikasi","end":""},{"old":"/riwayat-notifikasi/filter","type":0,"val":"filter","end":""}],
    types: placeholder as Registry['riwayatNotifikasi.filter']['types'],
  },
  'daftarPenerima.index': {
    methods: ["GET","HEAD"],
    pattern: '/daftar-penerima',
    tokens: [{"old":"/daftar-penerima","type":0,"val":"daftar-penerima","end":""}],
    types: placeholder as Registry['daftarPenerima.index']['types'],
  },
  'daftarPenerima.create': {
    methods: ["POST"],
    pattern: '/daftar-penerima/create',
    tokens: [{"old":"/daftar-penerima/create","type":0,"val":"daftar-penerima","end":""},{"old":"/daftar-penerima/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['daftarPenerima.create']['types'],
  },
  'daftarPenerima.search': {
    methods: ["GET","HEAD"],
    pattern: '/daftar-penerima/search',
    tokens: [{"old":"/daftar-penerima/search","type":0,"val":"daftar-penerima","end":""},{"old":"/daftar-penerima/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['daftarPenerima.search']['types'],
  },
  'daftarPenerima.edit': {
    methods: ["GET","HEAD"],
    pattern: '/daftar-penerima/edit/:id',
    tokens: [{"old":"/daftar-penerima/edit/:id","type":0,"val":"daftar-penerima","end":""},{"old":"/daftar-penerima/edit/:id","type":0,"val":"edit","end":""},{"old":"/daftar-penerima/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['daftarPenerima.edit']['types'],
  },
  'daftarPenerima.update': {
    methods: ["PUT"],
    pattern: '/daftar-penerima/update/:id',
    tokens: [{"old":"/daftar-penerima/update/:id","type":0,"val":"daftar-penerima","end":""},{"old":"/daftar-penerima/update/:id","type":0,"val":"update","end":""},{"old":"/daftar-penerima/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['daftarPenerima.update']['types'],
  },
  'daftarPenerima.destroy': {
    methods: ["DELETE"],
    pattern: '/daftar-penerima/delete/:id',
    tokens: [{"old":"/daftar-penerima/delete/:id","type":0,"val":"daftar-penerima","end":""},{"old":"/daftar-penerima/delete/:id","type":0,"val":"delete","end":""},{"old":"/daftar-penerima/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['daftarPenerima.destroy']['types'],
  },
  'tipeNotifikasi.index': {
    methods: ["GET","HEAD"],
    pattern: '/tipe-notifikasi',
    tokens: [{"old":"/tipe-notifikasi","type":0,"val":"tipe-notifikasi","end":""}],
    types: placeholder as Registry['tipeNotifikasi.index']['types'],
  },
  'tipeNotifikasi.create': {
    methods: ["POST"],
    pattern: '/tipe-notifikasi/create',
    tokens: [{"old":"/tipe-notifikasi/create","type":0,"val":"tipe-notifikasi","end":""},{"old":"/tipe-notifikasi/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['tipeNotifikasi.create']['types'],
  },
  'tipeNotifikasi.edit': {
    methods: ["GET","HEAD"],
    pattern: '/tipe-notifikasi/edit/:id',
    tokens: [{"old":"/tipe-notifikasi/edit/:id","type":0,"val":"tipe-notifikasi","end":""},{"old":"/tipe-notifikasi/edit/:id","type":0,"val":"edit","end":""},{"old":"/tipe-notifikasi/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipeNotifikasi.edit']['types'],
  },
  'tipeNotifikasi.update': {
    methods: ["PUT"],
    pattern: '/tipe-notifikasi/update/:id',
    tokens: [{"old":"/tipe-notifikasi/update/:id","type":0,"val":"tipe-notifikasi","end":""},{"old":"/tipe-notifikasi/update/:id","type":0,"val":"update","end":""},{"old":"/tipe-notifikasi/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipeNotifikasi.update']['types'],
  },
  'tipeNotifikasi.destroy': {
    methods: ["DELETE"],
    pattern: '/tipe-notifikasi/delete/:id',
    tokens: [{"old":"/tipe-notifikasi/delete/:id","type":0,"val":"tipe-notifikasi","end":""},{"old":"/tipe-notifikasi/delete/:id","type":0,"val":"delete","end":""},{"old":"/tipe-notifikasi/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tipeNotifikasi.destroy']['types'],
  },
  'tipeNotifikasi.search': {
    methods: ["GET","HEAD"],
    pattern: '/tipe-notifikasi/search',
    tokens: [{"old":"/tipe-notifikasi/search","type":0,"val":"tipe-notifikasi","end":""},{"old":"/tipe-notifikasi/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['tipeNotifikasi.search']['types'],
  },
  'templateNotifikasi.index': {
    methods: ["GET","HEAD"],
    pattern: '/template-notifikasi',
    tokens: [{"old":"/template-notifikasi","type":0,"val":"template-notifikasi","end":""}],
    types: placeholder as Registry['templateNotifikasi.index']['types'],
  },
  'templateNotifikasi.create': {
    methods: ["POST"],
    pattern: '/template-notifikasi/create',
    tokens: [{"old":"/template-notifikasi/create","type":0,"val":"template-notifikasi","end":""},{"old":"/template-notifikasi/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['templateNotifikasi.create']['types'],
  },
  'templateNotifikasi.search': {
    methods: ["GET","HEAD"],
    pattern: '/template-notifikasi/search',
    tokens: [{"old":"/template-notifikasi/search","type":0,"val":"template-notifikasi","end":""},{"old":"/template-notifikasi/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['templateNotifikasi.search']['types'],
  },
  'templateNotifikasi.edit': {
    methods: ["GET","HEAD"],
    pattern: '/template-notifikasi/edit/:id',
    tokens: [{"old":"/template-notifikasi/edit/:id","type":0,"val":"template-notifikasi","end":""},{"old":"/template-notifikasi/edit/:id","type":0,"val":"edit","end":""},{"old":"/template-notifikasi/edit/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templateNotifikasi.edit']['types'],
  },
  'templateNotifikasi.update': {
    methods: ["PUT"],
    pattern: '/template-notifikasi/update/:id',
    tokens: [{"old":"/template-notifikasi/update/:id","type":0,"val":"template-notifikasi","end":""},{"old":"/template-notifikasi/update/:id","type":0,"val":"update","end":""},{"old":"/template-notifikasi/update/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templateNotifikasi.update']['types'],
  },
  'templateNotifikasi.destroy': {
    methods: ["DELETE"],
    pattern: '/template-notifikasi/delete/:id',
    tokens: [{"old":"/template-notifikasi/delete/:id","type":0,"val":"template-notifikasi","end":""},{"old":"/template-notifikasi/delete/:id","type":0,"val":"delete","end":""},{"old":"/template-notifikasi/delete/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templateNotifikasi.destroy']['types'],
  },
  'pengguna.get_current_user': {
    methods: ["GET","HEAD"],
    pattern: '/current-user',
    tokens: [{"old":"/current-user","type":0,"val":"current-user","end":""}],
    types: placeholder as Registry['pengguna.get_current_user']['types'],
  },
  'auth.signOut': {
    methods: ["POST"],
    pattern: '/signout',
    tokens: [{"old":"/signout","type":0,"val":"signout","end":""}],
    types: placeholder as Registry['auth.signOut']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
